export default [
  {
    name: "Red sheep",
    description: "Pellentesque eget nunc.",
    author: "Issie Stedman",
    lastestRelease: "24/03/2021",
    chapters: 8,
    comments: 18,
    category: "modular",
    image: "http://dummyimage.com/200x300.png/5fa2dd/ffffff",
  },
  {
    name: "Squirrel, richardson's ground",
    description: "Aliquam sit amet diam in magna bibendum imperdiet.",
    author: "Zabrina Wilderspoon",
    lastestRelease: "01/06/2021",
    chapters: 18,
    comments: 9,
    category: "Exclusive",
    image: "http://dummyimage.com/200x300.png/ff4444/ffffff",
  },
  {
    name: "Bobcat",
    description:
      "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    author: "Marylou Stoakes",
    lastestRelease: "14/05/2021",
    chapters: 28,
    comments: 30,
    category: "fresh-thinking",
    image: "http://dummyimage.com/200x300.png/ff4444/ffffff",
  },
  {
    name: "Squirrel, pine",
    description:
      "Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.",
    author: "Gabriell Tyrer",
    lastestRelease: "13/05/2021",
    chapters: 37,
    comments: 32,
    category: "encryption",
    image: "http://dummyimage.com/200x300.png/5fa2dd/ffffff",
  },
  {
    name: "Sandpiper, spotted wood",
    description:
      "Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.",
    author: "Herminia Prate",
    lastestRelease: "10/04/2021",
    chapters: 45,
    comments: 47,
    category: "interactive",
    image: "http://dummyimage.com/200x300.png/ff4444/ffffff",
  },
  {
    name: "Porcupine, north american",
    description:
      "Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    author: "Chick Thomazin",
    lastestRelease: "18/03/2021",
    chapters: 29,
    comments: 46,
    category: "bifurcated",
    image: "http://dummyimage.com/200x300.png/ff4444/ffffff",
  },
  {
    name: "Egyptian vulture",
    description:
      "Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
    author: "Augustin Juppe",
    lastestRelease: "16/04/2021",
    chapters: 50,
    comments: 24,
    category: "Profound",
    image: "http://dummyimage.com/200x300.png/ff4444/ffffff",
  },
  {
    name: "Pacific gull",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.",
    author: "Reeba Caselli",
    lastestRelease: "09/03/2021",
    chapters: 17,
    comments: 7,
    category: "architecture",
    image: "http://dummyimage.com/200x300.png/5fa2dd/ffffff",
  },
  {
    name: "Flycatcher, tyrant",
    description:
      "Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    author: "Olwen Warden",
    lastestRelease: "02/06/2021",
    chapters: 5,
    comments: 48,
    category: "Configurable",
    image: "http://dummyimage.com/200x300.png/cc0000/ffffff",
  },
  {
    name: "Indian jackal",
    description:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.",
    author: "Kimbra Heintsch",
    lastestRelease: "19/05/2021",
    chapters: 11,
    comments: 7,
    category: "Programmable",
    image: "http://dummyimage.com/200x300.png/cc0000/ffffff",
  },
  {
    name: "Caracara, yellow-headed",
    description:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    author: "Hope Humberston",
    lastestRelease: "19/03/2021",
    chapters: 45,
    comments: 7,
    category: "national",
    image: "http://dummyimage.com/200x300.png/cc0000/ffffff",
  },
  {
    name: "Seal, northern elephant",
    description:
      "Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    author: "Christin McMaster",
    lastestRelease: "16/04/2021",
    chapters: 20,
    comments: 35,
    category: "Inverse",
    image: "http://dummyimage.com/200x300.png/cc0000/ffffff",
  },
  {
    name: "Black-backed magpie",
    description:
      "Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.",
    author: "Eddy Tilmouth",
    lastestRelease: "15/04/2021",
    chapters: 40,
    comments: 6,
    category: "next generation",
    image: "http://dummyimage.com/200x300.png/ff4444/ffffff",
  },
  {
    name: "Short-beaked echidna",
    description:
      "Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    author: "Ynes Margetson",
    lastestRelease: "24/01/2021",
    chapters: 28,
    comments: 40,
    category: "Fully-configurable",
    image: "http://dummyimage.com/200x300.png/cc0000/ffffff",
  },
  {
    name: "Bushbuck",
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.",
    author: "Rubia Farrants",
    lastestRelease: "23/01/2021",
    chapters: 14,
    comments: 30,
    category: "upward-trending",
    image: "http://dummyimage.com/200x300.png/5fa2dd/ffffff",
  },
  {
    name: "Galapagos penguin",
    description:
      "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
    author: "Nell Briffett",
    lastestRelease: "02/04/2021",
    chapters: 4,
    comments: 8,
    category: "Progressive",
    image: "http://dummyimage.com/200x300.png/dddddd/000000",
  },
  {
    name: "Lion, california sea",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    author: "Viviene Marriott",
    lastestRelease: "03/03/2021",
    chapters: 32,
    comments: 12,
    category: "database",
    image: "http://dummyimage.com/200x300.png/dddddd/000000",
  },
  {
    name: "Giant otter",
    description: "Proin at turpis a pede posuere nonummy. Integer non velit.",
    author: "Alphard Glazzard",
    lastestRelease: "24/02/2021",
    chapters: 21,
    comments: 31,
    category: "background",
    image: "http://dummyimage.com/200x300.png/5fa2dd/ffffff",
  },
  {
    name: "Cat, african wild",
    description:
      "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.",
    author: "Elyn Trytsman",
    lastestRelease: "12/03/2021",
    chapters: 42,
    comments: 9,
    category: "local",
    image: "http://dummyimage.com/200x300.png/cc0000/ffffff",
  },
  {
    name: "Manatee",
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
    author: "Chantal Colnet",
    lastestRelease: "01/03/2021",
    chapters: 49,
    comments: 35,
    category: "zero administration",
    image: "http://dummyimage.com/200x300.png/cc0000/ffffff",
  },
];
